# Generated by Django 2.0.13 on 2019-06-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0003_auto_20190608_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='toppings',
            name='description',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='toppings',
            name='large',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='toppings',
            name='price_large',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='toppings',
            name='price_small',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='toppings',
            name='small',
            field=models.FloatField(default=0.0),
        ),
    ]
