# Generated by Django 2.0.13 on 2019-06-27 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0006_auto_20190627_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='dinnerPlatters',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='pizza.DinnerPlatters'),
        ),
        migrations.AlterField(
            model_name='item',
            name='pasta',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='pizza.Pasta'),
        ),
        migrations.AlterField(
            model_name='item',
            name='regularPizza',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='pizza.RegularPizza'),
        ),
        migrations.AlterField(
            model_name='item',
            name='salads',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='pizza.Salads'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sicilianPizza',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='pizza.SicilianPizza'),
        ),
        migrations.AlterField(
            model_name='item',
            name='subs',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='pizza.Subs'),
        ),
    ]
