# Generated by Django 2.0.13 on 2019-06-28 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0007_auto_20190627_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='dinnerPlatters',
        ),
        migrations.RemoveField(
            model_name='item',
            name='pasta',
        ),
        migrations.RemoveField(
            model_name='item',
            name='regularPizza',
        ),
        migrations.RemoveField(
            model_name='item',
            name='salads',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sicilianPizza',
        ),
        migrations.RemoveField(
            model_name='item',
            name='subs',
        ),
        migrations.AddField(
            model_name='item',
            name='product_name',
            field=models.CharField(default='item_default', max_length=200),
        ),
        migrations.AddField(
            model_name='item',
            name='product_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='item',
            name='product_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='shoppingCart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pizza.ShoppingCart'),
        ),
    ]
