# Generated by Django 2.0.13 on 2019-06-29 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0009_auto_20190628_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='checked_out',
            field=models.BooleanField(default=False),
        ),
    ]
