# Generated by Django 2.0.13 on 2019-07-02 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0011_shoppingcart_date_of_checked_out'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_confirm', models.BooleanField(default=False)),
                ('date_of_confirm', models.DateTimeField(blank=True, null=True)),
                ('shoppingCart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza.ShoppingCart')),
            ],
        ),
    ]
